version: "3.9"
services:
  resenhas:
    build: ./ResenhasServ
    ports:
      - "8002:8002"
  livros:
    build: ./LivrosServ
    ports:
      - "8003:8003"
  cred:
    build: ./CredServ
    ports:
      - "8000:8000"
  apigateway:
    build: ./ApiGateway
    ports:
      - "7999:7999"